[package]
name = "rainbowgif"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
palette = "0.6.0"
gif = "0.11.3"
gif-dispose = "3.1.1"
